apiVersion: v1
kind: Service
metadata:
   name: knative-service
   namespace: testkube
spec:
   clusterIP: None
   ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
   type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: knative-service
  namespace: testkube
subsets:
  - addresses:
    - ip: 192.168.2.102
    ports:
      - port: 8080
