name: 'Testkube Cloud CLI'
description: 'Testkube command running directly on a managed cluster in a Cloud Provider'
inputs:
  provider:
    description: 'Cloud provider'
    required: true
    default: 'gcp'
  sa-key:
    description: 'Service Account Key'
    required: true
    default: ''
  project:
    description: 'Project ID'
    required: true
    default: ''
  cluster-name:
    description: 'Cluster name'
    required: true
    default: ''
  zone:
    description: 'Location'
    required: true
    default: ''
  command:
    description: 'Command'
    required: true
    default: 'get'
  resource:
    description: 'Resource'
    required: false
    default: 'tests'
  namespace:
    description: 'Namespace'
    required: false
    default: 'testkube'
  api-key:
    description: 'API key'
    required: false
    default: ''
  api-uri:
    description: 'API uri'
    required: false
    default: ''
  parameters:
    description: 'Parameters'
    required: false
    default: ''
  stdin:
    description: 'Standard input'
    required: false
    default: ''
output:
runs:
  using: "composite"
  steps:
    - name: 'gcloud login'
      if: ${{ inputs.provider }} == 'gcp'
      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ inputs.sa-key }}
        project_id: ${{ inputs.project }}
    - name: 'Set GKE credentials'
      if: ${{ inputs.provider }} == 'gcp'
      uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ inputs.cluster-name }}
        location: ${{ inputs.zone }}
        credentials: ${{ inputs.sa-key }}
    - name: Run Testkube
      uses: kubeshop/testkube-docker-action@v1
      with:
        command: ${{ inputs.command }}
        resource: ${{ inputs.resource }}
        namespace: ${{ inputs.namespace }}
        api-key: ${{ inputs.api-key }}
        api-uri: ${{ inputs.api-uri }}
        parameters: ${{ inputs.parameters }}
        stdin: ${{ inputs.stdin }}
