name: kubepug
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
      - name: Install Testkube
        run: |
          wget -qO - https://repo.testkube.io/key.pub | sudo apt-key add -
          echo "deb https://repo.testkube.io/linux linux main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y testkube
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run on local file
        run: |
          kubectl testkube create test --file example-manifest.yaml --type kubepug/yaml --name kubepug-file-test
          kubectl run test kubepug-file-test
      - name: Use Testkube dev cluster
        run: ls
      - name: Run
        run: ls # |
          #kubectl get ingress some-invalid-ingress | kubectl testkube create test --name kubepug-test
          #kubectl run test kubepug-test

