name: testkube-gke-action
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Set unique var
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Test Action
        uses: ./.github/actions/testkube-gke
        with:
          gke-sa-key: ${{ secrets.GKE_SA_KEY }}
          gke-project-id: ${{ secrets.GKE_PROJECT }}
          gke-cluster-name: ${{ secrets.GKE_CLUSTER_NAME_DEV }}
          gke-zone: ${{ secrets.GKE_ZONE_DEV }}
          command: 'run'
          resource: 'test'
          namespace: 'testkube'
          parameters: 'successful-soapui'
