name: testkube-gke-action-failure
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: kubeshop/testkube-cloud-action@v1.0.0
        with:
          provider: 'gcp'
          sa-key: ${{ secrets.GKE_SA_KEY }}
          project: ${{ secrets.GKE_PROJECT }}
          cluster-name: ${{ secrets.GKE_CLUSTER_NAME_DEV }}
          zone: ${{ secrets.GKE_ZONE_DEV }}
          command: 'run'
          resource: 'test'
          namespace: 'testkube'
          parameters: 'failing-soapui -f'
